<?xml version="1.0"?>

<!DOCTYPE rezept [
<!ATTLIST rezept  xml:lang  CDATA  #IMPLIED>
<!ELEMENT rezept  (zutat*, anleitung*)>
<!ELEMENT zutat  (#PCDATA)>
<!ATTLIST zutat  id ID #IMPLIED>
<!ATTLIST zutat  xml:lang  CDATA  #IMPLIED>
<!ATTLIST zutat  xmlns:xlink  CDATA  #IMPLIED>
<!ATTLIST zutat  xlink:type  CDATA  #IMPLIED>
<!ATTLIST zutat  xlink:href  CDATA  #IMPLIED>
<!ELEMENT anleitung (#PCDATA)>
]>

<?xml-stylesheet href="style.xsl" type="text/xml"?>
<rezept>
   <zutat id="mehl">200g Mehl</zutat>
   <zutat id="mehl">z 2</zutat>
   <zutat id="mehl">z 3</zutat>
   <!-- weitere Zutaten -->
   <anleitung>
      Zuerst nehmen Sie das
      <zutat xmlns:xlink="http://www.w3.org/1999/xlink"
             xlink:type="simple" xlink:href="mehl">Mehl</zutat>
      und mischen es mit ...
   </anleitung>
</rezept>